name: cicd-api

# on:
#   push:
#     branches:
#       - main

on:
  pull_request:
    types: [labeled]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'stage')

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (clone repo)
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Create deployment package
        run: |
          pip install pipenv --user
          cd source          
          pipenv install --deploy --ignore-pipfile
          mkdir package
          cp -r $(pipenv --venv)/lib/python3.8/site-packages/* package/
          cd package
          zip -r ../lambda_deployment_package.zip .
          cd ..
          zip lambda_deployment_package.zip lambda_function.py

      - name: Upload lambda deployment package
        uses: actions/upload-artifact@v3
        with:
          name: lambda_package
          path: source

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: lambda_package
          path: "."

      - name: Credentials to make AWS API calls
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::955124475810:role/github-oidc-role-Role-qqiSGM6xVeeT

      - name: Update lambda code
        run: |
          aws lambda update-function-code --function-name lambda_function --zip-file fileb://lambda_deployment_package.zip

  smoke-test:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Checkout code (clone repo)
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Credentials to make AWS API calls
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::955124475810:role/github-oidc-role-Role-qqiSGM6xVeeT

      - name: Run smoke test
        run: |
          pip install pipenv --user
          cd tests    
          pipenv install --deploy --ignore-pipfile
          pipenv run python smoke_test_api_to_db.py
